spring:
  application:
    name: tiniProjectBackend
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://mariadb-container:3306/tini_db
    username: tini
    password: T!N!2@2b
    hikari:
      max-lifetime: 57000
      maximum-pool-size: 24
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    show_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true

  mongodb:
    uri: mongodb://tiniUser:TlNi0I$@mongoDB:27017/tini_mongodb?authSource=tini_mongodb